### ISSUE TITLE
Kuka arm state doesn't change in GUI

### ISSUE THREAD

**Issue by OmkarKabadagi5823** [adamheins/pyb_utils#1]
## Issue
While executing the `collision_detection_example.py`, the robot state is being changed in the back-end but the robot state does not reflect on the GUI. 
![image](https://user-images.githubusercontent.com/55598261/192592607-e1f68084-fa73-4f7f-bab6-13ce7df2ace5.png)

As you can see in the image, the robot is in a collision state, but the actual state is not being reflected on the GUI.

## Fix
Upon inspecting the code I saw that there are two separate bullet clients, one is `gui_id` connected to `pyb.GUI` and `col_id` connected to the back-end `pyb.DIRECT` and in `collision.py` file the `CollisionDetector.compute_distances` function is only updating the state in `col_id` but not in `gui_id`  

```python
# put the robot in the given configuration
for i in range(pyb.getNumJoints(self.robot_id, physicsClientId=self.col_id)):
    pyb.resetJointState(self.robot_id, i, q[i], physicsClientId=self.col_id)
```
Simple fix is to pass `gui_id` also to the `CollisionDetector` class and update the state for `gui_id` also.

```python
# put the robot in the given configuration
for i in range(pyb.getNumJoints(self.robot_id, physicsClientId=self.col_id)):
    pyb.resetJointState(self.robot_id, i, q[i], physicsClientId=self.col_id)
    pyb.resetJointState(self.robot_id, i, q[i], physicsClientId=self.gui_id)
```

I have verified this and the poses now also update on the GUI

![image](https://user-images.githubusercontent.com/55598261/192596233-c38ce5e4-64af-4525-a217-2c1ed9c4392c.png)

I am submitting a pull request to fix the issue.

**Comment by adamheins** [comment]
This is in fact expected behaviour: we would like to be able to check if an arbitrary configuration is in collision without actually moving the main GUI-based simulated robot to that configuration. This is useful for e.g. motion planning, where a planner would consider many configurations without actually moving to them.

**Comment by OmkarKabadagi5823** [comment]
Alright. Now I understand why you aren't updating the gui (I also later read a comment in the code saying this behavior is expected). Because you are expecting the code to be used as a utility library, you wouldn't want it to update the GUI. 

But I still found the collision detection example to be somewhat non-intuitive. The reason is because, the states being checked in collision are at random. So, even though the code prints that a state is in collision or not, I am visually unaware what those state look like.

I would propose the example to follow a fixed trajectory and then also update that on the GUI (where gui updation is only part of the example an not the utility classes themselves), unless it is in collision. 

I will the decision to you whether you want it to leave the example as is. I would like to make the changes in the example as suggested above, if you allow, in a new pull request. You can cancel this one.

Thanks btw. Nice utility tool.

**Comment by adamheins** [comment]
You make a good point: I agree the collision detection example isn't very intuitive at the moment. In addition to visually showing when the robot is in collision, I'd also like to make sure it is clear that one can also check for collisions of arbitrary configurations *without* affecting the main GUI sim. Ideally, the example would convey both ideas clearly, but I'm not entirely sure the best way to do so.

**Comment by OmkarKabadagi5823** [comment]
How about adding `UserDebugParameter` for each joint to update the arm configuration? This would allow user to use the sliders on the GUI to set arbitrary positions and if a particular configuration in is collision, it would not update the GUI state and display in the terminal that the state leads to collision.

**Comment by adamheins** [comment]
That sounds like a reasonable thing to do. If you'd like to make a PR along those lines, I'd be happy to take a look at it.

**Comment by OmkarKabadagi5823** [comment]
Sure. I would be happy to work on it. I that case, I will close the old PR and submit a new one once I am done.

**Comment by OmkarKabadagi5823** [comment]
I have added the mentioned features to the example. The description and screenshots are in the PR description.
